config/routes.rb
Rails.application.routes.draw do
  resources :configuracaos

  get 'administracao/listagem_funcionarios'
  get 'administracao/criar_funcionario'
  get 'administracao/editar_funcionario'
  post 'administracao/salvar_funcionario'
  post 'administracao/atualizar_funcionario'
  get 'administracao/detalhes_funcionario'
  get 'administracao/relatorio_quantitativo_professor'
  get 'administracao/relatorio_quantitativo'
  get 'administracao/relatorio_nominal_geral'
  get "administracao/autocomplete_local_nome"
  get "administracao/relatorio_sem_cadastro"

      devise_for :usuarios#, :controllers => {:registrations => "registrations"}
      resources :funcionarios do
        get :autocomplete_local_nome,:on=>:collection
        get :funcionario_professor
      end

      scope "/admin", as: "admin" do
        resources :disciplinas
        resources :usuarios do
          get :autocomplete_local_nome,:on=>:collection
        end
        resources :locals do
          get 'resumo_escola'
        end
      end

  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'

end

app/models/configuracao.rb
class Configuracao
	include Mongoid::Document
	field :periodo_inicio, type: DateTime
	field :periodo_fim, type: DateTime
	field :aberto_escolas, type: Mongoid::Boolean
	field :aberto_departamento, type: Mongoid::Boolean
	field :aberto_escolas_rurais,type: Mongoid::Boolean
	field :ativa,type: Mongoid::Boolean
end

app/controllers/configuracaos_controller.rb
class ConfiguracaosController < ApplicationController
  before_action :set_configuracao, only: [:show, :edit, :update, :destroy]
 before_action :dados,:admin

  # GET /configuracaos
  # GET /configuracaos.json
  def index
    @configuracaos = Configuracao.all
  end

  # GET /configuracaos/1
  # GET /configuracaos/1.json
  def show
  end

  # GET /configuracaos/new
  def new
    @configuracao = Configuracao.new
  end

  # GET /configuracaos/1/edit
  def edit
  end

  # POST /configuracaos
  # POST /configuracaos.json
  def create
    @configuracao = Configuracao.new(configuracao_params)

    respond_to do |format|
      if @configuracao.save
        format.html { redirect_to @configuracao, notice: 'Configuracao was successfully created.' }
        format.json { render :show, status: :created, location: @configuracao }
      else
        format.html { render :new }
        format.json { render json: @configuracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configuracaos/1
  # PATCH/PUT /configuracaos/1.json
  def update
    respond_to do |format|
      if @configuracao.update(configuracao_params)
        format.html { redirect_to @configuracao, notice: 'Configuracao was successfully updated.' }
        format.json { render :show, status: :ok, location: @configuracao }
      else
        format.html { render :edit }
        format.json { render json: @configuracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configuracaos/1
  # DELETE /configuracaos/1.json
  def destroy
    @configuracao.destroy
    respond_to do |format|
      format.html { redirect_to configuracaos_url, notice: 'Configuracao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuracao
      @configuracao = Configuracao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def configuracao_params
      params.require(:configuracao).permit(:ativa,:periodo_inicio, :periodo_fim, :aberto_escolas,:aberto_escolas_rurais, :aberto_departamento)
    end
end

app/helpers/configuracaos_helper.rb
module ConfiguracaosHelper
	def aberto
		config = Configuracao.where(:periodo_inicio.lt=>Time.now,:periodo_fim.gte=>Time.now)
		local = current_usuario.local
		tipo = 'escola' if local.escola?
		tipo = 'setorial' if !local.escola?
		tipo = 'escola_rural' if local.escola? and local.municipio and local.municipio.nome!="Macapá" and local.municipio.nome!="Santana"
		if !config.none? and config.where(:aberto_escolas=>true).any? and tipo=='escola'
			return true
		elsif !config.none? and config.where(:aberto_escolas_rurais=>true).any? and tipo=='escola_rural'
			return true
		elsif !config.none? and config.where(:aberto_departamento=>true).any? and tipo=="setorial"
			return true
		elsif current_usuario.aberto?
			return true
		else 
			return false
		end
	end
end

app/views/configuracaos/_form.html.erb
<%= simple_form_for @configuracao, :html => { :class => 'form-horizontal' } do |f| %>
  <% if !@configuracao.periodo_inicio.blank?%>
  <%= f.input :periodo_inicio,input_html: {class:"datetime",value: @configuracao.periodo_inicio.strftime("%d/%m/%Y %T")} %>
  <% else %>
  <%= f.input :periodo_inicio,input_html: {class:"datetime"} %>
  <% end %>
  <%= error_span(@configuracao[:periodo_inicio]) %>
   <% if !@configuracao.periodo_inicio.blank?%>
  <%= f.input :periodo_fim,input_html: {class:"datetime",value: @configuracao.periodo_fim.strftime("%d/%m/%Y %T")} %>
  <% else %>
  <%= f.input :periodo_fim,input_html: {class:"datetime"} %>
  <% end %>
  <%= error_span(@configuracao[:periodo_fim]) %>
  <%= f.input :aberto_escolas,:collection=>@boolean %>
  <%= error_span(@configuracao[:aberto_escolas]) %>
  <%= f.input :aberto_escolas_rurais,:collection=>@boolean %>
  <%= error_span(@configuracao[:aberto_escolas]) %>
  <%= f.input :aberto_departamento,:collection=>@boolean%>
  <%= error_span(@configuracao[:aberto_departamento]) %>
   <%= f.input :ativa,:collection=>@boolean%>
  <%= error_span(@configuracao[:ativa]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                configuracaos_path, :class => 'btn btn-default' %>
<% end %>

app/views/configuracaos/edit.html.erb
<%- model_class = Configuracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/configuracaos/index.html.erb
<%- model_class = Configuracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:periodo_inicio) %></th>
      <th><%= model_class.human_attribute_name(:periodo_fim) %></th>
      <th><%= model_class.human_attribute_name(:aberto_escolas) %></th>
      <th><%= model_class.human_attribute_name(:aberto_departamento) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @configuracaos.each do |configuracao| %>
      <tr>
        <td><%= link_to configuracao.id, configuracao_path(configuracao) %></td>
        <td><%= configuracao.periodo_inicio %></td>
        <td><%= configuracao.periodo_fim %></td>
        <td><%= configuracao.aberto_escolas %></td>
        <td><%= configuracao.aberto_departamento %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_configuracao_path(configuracao), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      configuracao_path(configuracao),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_configuracao_path,
            :class => 'btn btn-primary' %>

app/views/configuracaos/new.html.erb
<%- model_class = Configuracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/configuracaos/show.html.erb
<%- model_class = Configuracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:periodo_inicio) %>:</strong></dt>
  <dd><%= @configuracao.periodo_inicio.strftime("%d/%m/%Y %T") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:periodo_fim) %>:</strong></dt>
  <dd><%= @configuracao.periodo_fim.strftime("%d/%m/%Y %T") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:aberto_escolas) %>:</strong></dt>
  <dd><%= objeto_valor(@configuracao.aberto_escolas) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:aberto_departamento) %>:</strong></dt>
  <dd><%= objeto_valor(@configuracao.aberto_departamento) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              configuracaos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_configuracao_path(@configuracao), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              configuracao_path(@configuracao),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>