config/routes.rb
Rails.application.routes.draw do
  resources :configuracaos

  get 'administracao/listagem_funcionarios'
  get 'administracao/criar_funcionario'
  get 'administracao/editar_funcionario'
  post 'administracao/salvar_funcionario'
  post 'administracao/atualizar_funcionario'
  get 'administracao/detalhes_funcionario'
  get 'administracao/relatorio_quantitativo_professor'
  get 'administracao/relatorio_quantitativo'
  get 'administracao/relatorio_nominal_geral'
  get "administracao/autocomplete_local_nome"
  get "administracao/relatorio_sem_cadastro"

      devise_for :usuarios#, :controllers => {:registrations => "registrations"}
      resources :funcionarios do
        get :autocomplete_local_nome,:on=>:collection
        get :funcionario_professor
      end

      scope "/admin", as: "admin" do
        resources :disciplinas
        resources :usuarios do
          get :autocomplete_local_nome,:on=>:collection
        end
        resources :locals do
          get 'resumo_escola'
        end
      end

  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'

end

app/views/shared/_menu_relatorios.html.erb
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-expanded="true">
   Gestão
   <span class="caret"></span>
 </button>
 <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
  <li role="presentation"><%= link_to('Relatório quantitativo de professores por disciplina', administracao_relatorio_quantitativo_path) %></li>
  <li role="presentation"><%= link_to 'Listagem de Funcionarios', administracao_listagem_funcionarios_path %></li>
  <li role="presentation"><%= link_to 'Listagem de Setoriais', admin_locals_path if current_usuario.admin?%></li>
  <li role="presentation"><%= link_to 'Listagem de Disciplinas', admin_disciplinas_path  if current_usuario.admin?%></li>
  <li role="presentation"><%= link_to 'Listagem de Usuários', admin_usuarios_path  if current_usuario.admin?%></li>
</ul>
</div>