config/routes.rb
Rails.application.routes.draw do
  resources :configuracaos

  get 'administracao/listagem_funcionarios'
  get 'administracao/criar_funcionario'
  get 'administracao/editar_funcionario'
  post 'administracao/salvar_funcionario'
  post 'administracao/atualizar_funcionario'
  get 'administracao/detalhes_funcionario'
  get 'administracao/relatorio_quantitativo_professor'
  get 'administracao/relatorio_quantitativo'
  get 'administracao/relatorio_nominal_geral'
  get "administracao/autocomplete_local_nome"
  get "administracao/relatorio_sem_cadastro"

      devise_for :usuarios#, :controllers => {:registrations => "registrations"}
      resources :funcionarios do
        get :autocomplete_local_nome,:on=>:collection
        get :funcionario_professor
      end

      scope "/admin", as: "admin" do
        resources :disciplinas
        resources :usuarios do
          get :autocomplete_local_nome,:on=>:collection
        end
        resources :locals do
          get 'resumo_escola'
        end
      end

  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  get '/', :to => 'administracao#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'

end

app/models/funcionario.rb
class Funcionario
  include Mongoid::Document
  field :nome, type: String
  field :cpf, type: String
  field :cadastro, type: String
  field :classe, type: String
  field :padrao, type: Integer
  field :turmas, type: Integer
  field :carga_horaria, type: String
  field :ambiente, type: String
  field :ambiente_nao_docente, type: String
  field :formacao, type: String
  field :ch_em_sala,type: Integer
  field :cargo, type: String
  field :quadro, type: String
  field :concurso, type: String
  field :area_concurso, type: String
  field :programa, type: String
  field :situacao, type: String
  field :documento, type: String
  field :diretor_ou_secretario,type: Boolean,default: false
  field :componente_curricular
  scope :do_quadro, ->(quadro) { where(:quadro => quadro) }
  scope :do_cargo, ->(cargo) { where(:cargo => cargo) }
  belongs_to :local
  belongs_to :usuario
  belongs_to :disciplina_concurso,:class_name=>"Disciplina",:inverse_of=>:funcionarios
  belongs_to :disciplina_atuacao,:class_name=>"Disciplina",:inverse_of=>:funcionarios_atuando
  belongs_to :municipio_concurso,:class_name=>"Municipio"
  validate :validar_local
  validates_presence_of :nome,:cpf,:cargo,:carga_horaria,:quadro,message: "Informação necessária"
  validates_presence_of :classe,:municipio_concurso,:situacao,:concurso,if:  Proc.new { |a| self.quadro=="Estadual"},message: "Informação necessária"
  validates_presence_of :disciplina_concurso,if:  Proc.new { |a| a.cargo=="Professor" and (self.quadro=="Estadual" or self.quadro=="Federal")},message: "Informação necessária"
  validates_presence_of :disciplina_atuacao,:turmas,:ch_em_sala,if:  Proc.new { |a| a.ambiente=="Sala de Aula" and a.situacao=="Ativo" and !a.local.escola?}
  validates_presence_of :programa,if:  Proc.new { |a| a.cargo.include?("Programa") and a.situacao=="Ativo" },message: "Informação necessária"
  validate :validate_cadastro
  validate :cpf_valido
  validate :validate_ambiente,if: Proc.new { |a| a.local and a.local.escola}
  delegate :nome, to: :local, prefix: true, :allow_nil => true

  #Validaçoes antigas
  #validates_presence_of :cadastro,if:  Proc.new { |a| !a.quadro=="Contrato Administrativo"},message: "Informação necessária"
  #validates_presence_of :ambiente,message: "Informação necessária",:if=>Proc.new{|a|a.ambiente_nao_docente.blank? or (a.situacao.include?("Ativo") or a.situacao.include?("Acompanhado"))}
  
  validates_uniqueness_of :cadastro,scope: :local,:if=>Proc.new { |a|!a.quadro.include?("Contrato")},message: "Já está cadastrado"
  validates_uniqueness_of :cpf,scope: :cadastro,:if=>Proc.new { |a|!a.quadro.include?("Contrato")},message: "Já está cadastrado"
  validates_uniqueness_of :cpf,:if=>Proc.new { |a|a.quadro.include?("Contrato")},message: "Já está cadastrado"
  before_save :pos_ambiente
  before_save :nome_maiusculo

  def cpf_valido
    cpf = Cpf.new(self.cpf)
    if !cpf.valido?
     errors.add(:cpf, "não é valido")
   end
 end

 def validar_local
  if self.local.nil?
    errors.add(:local_nome, "Informação necessária")
  end
 end

 def validate_ambiente
  if self.cargo!="Professor" and self.ambiente_nao_docente.blank? and (self.situacao=="Ativo" or self.situacao=="Acompanhado pela Casa do Professor" or self.situacao=="Ativo mas em sala ambiente perante perícia médica")
    errors.add(:ambiente_nao_docente, "Informação necessária")
  elsif self.cargo=="Professor" and self.ambiente.blank? and (self.situacao=="Ativo" or self.situacao=="Acompanhado pela Casa do Professor" or self.situacao=="Ativo mas em sala ambiente perante perícia médica")
     errors.add(:ambiente, "Informação necessária")
  end
end

def validate_cadastro
  if self.cadastro.blank? and !self.quadro.include?("Contrato")
    errors.add(:cadastro, "Informação necessária")
  end
end

def pos_ambiente
  if !self.ambiente_nao_docente.blank? and self.cargo!="Professor"
    self.ambiente = self.ambiente_nao_docente
  elsif self.ambiente_nao_docente.blank? and self.cargo!="Professor"
    self.ambiente = ""
  end
end

def nome_maiusculo
  if !self.nome.blank?
    self.nome = self.nome.upcase
  end
end


end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]
  before_action :mudar_senha
  before_filter :dados
  before_filter :redir_editores
  #autocomplete :local,:nome,:full=>true

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @usuario = current_usuario
    @funcionarios = @usuario.local.funcionarios.asc(:nome)
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)
    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionário cadastrado com sucesso' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionário atualizado.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit,:alert=>"Erros no cadastro, favor checar" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionário apagado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit([:componente_curricular,:nome, :cpf, :cadastro, :classe, :padrao, :turmas, :carga_horaria, :ambiente,:ambiente_nao_docente, :formacao, :ch_em_sala, :cargo, :quadro, :concurso, :area_concurso, :programa, :situacao, :local_id,:local, :disciplina_concurso, :disciplina_atuacao, :municipio_concurso])
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
	def carga_horaria(obj)
		if (obj.is_a?(String) or obj.is_a?(Integer)) and !obj.blank?
			return "#{obj} Horas"
		else
			return "Nada Cadastrado"
		end
	end

	def ambiente_alerta(obj)
		if obj.local.escola and obj.ambiente.blank? and (obj.situacao=="Ativo" or obj.situacao=="Acompanhado pela Casa do Professor" or obj.situacao=="Ativo mas em sala ambiente perante perícia médica")
			return raw "<b style='color: red;'>Nada cadastrado</b>"
		elsif !obj.ambiente.blank?
			return obj.ambiente
		else
			return "Nada Cadastrado"
		end
	end
	def ch_turmas(obj)
		if !obj.ch_em_sala.nil? and !obj.turmas.nil?
			return "#{obj.ch_em_sala} H/Aula"
		elsif !obj.ch_em_sala.nil? and obj.turmas.nil?
			return "#{obj.ch_em_sala} H/Aula"
		elsif obj.ch_em_sala.nil? and !obj.turmas.nil?
			return "#{obj.turmas} Turmas"
		else
			return "N/A"
		end

	end
end

app/views/funcionarios/_form_escola.html.erb
<%= simple_form_for @funcionario, :html => { :class => 'form-condensed' } do |f| %>

<%= f.input :local_id,:as=>:hidden,:input_html=>{:value=>current_usuario.local_id} %>

<%= f.input :nome %>
<%= error_span(@funcionario[:nome]) %>
<%= f.input :cpf,:label=>"CPF",:input_html=>{:class=>"cpf"} %>
<%= error_span(@funcionario[:cpf]) %>
<%= f.label "Cadastro¹"%> <i>¹não é necessário preencher este campo para o Contrato Administrativo.</i>
<%= f.input :cadastro,:label=>false%>
<%= error_span(@funcionario[:cadastro]) %>
<%= f.input :cargo,:collection=>@cargos,:label=>"Cargo"%>
<%= error_span(@funcionario[:cargo]) %>
<%= f.input :quadro,:collection=>@quadros %>

<%= error_span(@funcionario[:quadro]) %>
<div class="js-dependent-fields" data-select-id='funcionario_quadro' data-option-value='Estadual|Federal'>
	<%= f.label "Diretor(a) ou Secretário(a) que está em sala de Aula ou Coordenação de Programas Federais/Estaduais" %>
	<%= f.input :diretor_ou_secretario,label: "Este funcionário é Diretor ou Secretário e está em sala de aula ou cordenação de programas?",as: :boolean %>
	<%= error_span(@funcionario[:diretor_ou_secretario]) %>
	<%= f.input :classe,:collection=>@classes %>
	<%= error_span(@funcionario[:classe]) %>
	<% if @funcionario.municipio_concurso%>
	<%= f.input :municipio_concurso,:label=>"Município do Concurso",:collection=>@municipios,:selected=>@funcionario.municipio_concurso_id%>
	<% else %>
	<%= f.input :municipio_concurso,:label=>"Município do Concurso",:collection=>@municipios%>
	<% end %>
	<%= error_span(@funcionario[:municipio_concurso]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_municipio_concurso' data-option-value='<%=Municipio.find_by(:nome=>'Macapá').id%>|<%=Municipio.find_by(:nome=>'Santana').id%>'>
		<%= f.input :area_concurso,:label=>"Área do Concurso",:collection=>["Urbana","Rural"] %>
		<%= error_span(@funcionario[:area_concurso]) %>
	</div>
	<%= f.input :situacao,:label=>"Situação",:collection=>@situacoes %>
	<%= error_span(@funcionario[:situacao]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='Professor'>
		<% if @funcionario.disciplina_concurso%>
		<%= f.input :disciplina_concurso,:label=>"Disciplina do Concurso",:collection=>@disciplinas,:selected=>@funcionario.disciplina_concurso_id%>
		<% else %>
		<%= f.input :disciplina_concurso,:label=>"Disciplina do Concurso",:collection=>@disciplinas%>
		<% end %>
		<%= error_span(@funcionario[:disciplina_concurso]) %>
	</div>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_quadro' data-option-value='Estadual'>
	<%= f.input :concurso,:collection=>@concursos %>
	<%= error_span(@funcionario[:concurso]) %>
</div>
<%= f.input :carga_horaria,:collection=>@cargas_horarias,:label=>"Carga Horária do vínculo" %>
<%= error_span(@funcionario[:carga_horaria]) %>

<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='Professor'>
	<%= f.input :ambiente,:collection=>@ambientesprof %>
	<%= error_span(@funcionario[:ambiente]) %>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='<%=((@cargos-['Professor']).join("|").html_safe)%>'>
	<%= f.input :ambiente_nao_docente,:label=>"Ambiente",:collection=>@ambientes %>
	<%= error_span(@funcionario[:ambiente_nao_docente]) %>
</div>

<div class="js-dependent-fields" data-select-id='funcionario_ambiente' data-option-value='Sala de Aula'>
	<%if @funcionario.disciplina_atuacao%>
	<%= f.input :disciplina_atuacao,:collection=>@disciplinas,:selected=>@funcionario.disciplina_atuacao_id %>
	<%else%>
	<%= f.input :disciplina_atuacao,:collection=>@disciplinas%>
	<%end%>
	
	<%= error_span(@funcionario[:disciplina_atuacao]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_disciplina_atuacao' data-option-value='<%= Disciplina.where(:nome=>"Educação Profissional").first.id%>'>
		<%= f.label "Componente Curricular²"%> <i>² Somente para educação Profissional</i>
		<%= f.input :componente_curricular,:label=>false%>
	</div>
	<%= f.input :turmas,:label=>"Numero de Turmas",:as=>:integer %>
	<%= error_span(@funcionario[:turmas]) %>
	<%= f.input :ch_em_sala,:label=>"Carga Horária em sala",:as=>:integer %>
	<%= error_span(@funcionario[:ch_em_sala]) %>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_ambiente' data-option-value='Coordenação de Programa Estadual|Coordenação de Programa Federal'>
	<%= f.input :programa,:label=>"Nome do Programa" %>
	<%= error_span(@funcionario[:programa]) %>
</div>
<%#= f.input :local,:url=>autocomplete_local_nome_funcionarios_path,:as=>:autocomplete %>


<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
funcionarios_path, :class => 'btn btn-default' %>
<% end %>

app/views/funcionarios/_form_secretaria.html.erb
<%= simple_form_for @funcionario, :html => { :class => 'form-condensed' } do |f| %>

<%= f.input :local_id,:as=>:hidden,:input_html=>{:value=>current_usuario.local_id} %>

<%= f.input :nome %>
<%= error_span(@funcionario[:nome]) %>
<%= f.input :cpf,:label=>"CPF",:input_html=>{:class=>"cpf"} %>
<%= error_span(@funcionario[:cpf]) %>
<%= f.label "Cadastro¹"%> <i>¹não é necessário preencher este campo para o Contrato Administrativo.</i>
<%= f.input :cadastro,:label=>false%>
<%= error_span(@funcionario[:cadastro]) %>
<%= f.input :cargo,:collection=>@cargos,:label=>"Cargo"%>
<%= error_span(@funcionario[:cargo]) %>
<%= f.input :quadro,:collection=>@quadros %>

<%= error_span(@funcionario[:quadro]) %>
<div class="js-dependent-fields" data-select-id='funcionario_quadro' data-option-value='Estadual|Federal'>
	<%= f.input :classe,:collection=>@classes %>
	<%= error_span(@funcionario[:classe]) %>
	<% if @funcionario.municipio_concurso%>
	<%= f.input :municipio_concurso,:label=>"Município do Concurso",:collection=>@municipios,:selected=>@funcionario.municipio_concurso_id%>
	<% else %>
	<%= f.input :municipio_concurso,:label=>"Município do Concurso",:collection=>@municipios%>
	<% end %>
	<%= error_span(@funcionario[:municipio_concurso]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_municipio_concurso' data-option-value='<%=Municipio.find_by(:nome=>'Macapá').id%>|<%=Municipio.find_by(:nome=>'Santana').id%>'>
		<%= f.input :area_concurso,:label=>"Área do Concurso",:collection=>["Urbana","Rural"] %>
		<%= error_span(@funcionario[:area_concurso]) %>
	</div>
	<%= f.input :situacao,:label=>"Situação",:collection=>@situacoes %>
	<%= error_span(@funcionario[:situacao]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='Professor'>
		<% if @funcionario.disciplina_concurso%>
		<%= f.input :disciplina_concurso,:label=>"Disciplina do Concurso",:collection=>@disciplinas,:selected=>@funcionario.disciplina_concurso_id%>
		<% else %>
		<%= f.input :disciplina_concurso,:label=>"Disciplina do Concurso",:collection=>@disciplinas%>
		<% end %>
		<%= error_span(@funcionario[:disciplina_concurso]) %>
	</div>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_quadro' data-option-value='Estadual'>
	<%= f.input :concurso,:collection=>@concursos %>
	<%= error_span(@funcionario[:concurso]) %>
</div>
<%= f.input :carga_horaria,:collection=>@cargas_horarias,:label=>"Carga Horária do vínculo" %>
<%= error_span(@funcionario[:carga_horaria]) %>


<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
funcionarios_path, :class => 'btn btn-default' %>
<% end %>

app/views/funcionarios/edit.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>
<%= render :partial => 'form_escola' if current_usuario.local.escola?%>
<%= render :partial => 'form_secretaria' if !current_usuario.local.escola?%>

app/views/funcionarios/index.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:cadastro) %></th>
      <th><%= model_class.human_attribute_name(:carga_horaria) %></th>
      <% if current_usuario.local.escola%>
      <th><%= model_class.human_attribute_name(:ambiente) %></th>
      <%end%>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:quadro) %></th>
      <th><%= model_class.human_attribute_name(:situacao) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_concurso_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @funcionarios.each do |funcionario| %>
    <tr>
      <td><%= link_to funcionario.nome,funcionario_path(funcionario) %></td>
      <td><%= objeto_valor(funcionario.cpf) %></td>
      <td><%= objeto_valor(funcionario.cadastro) %></td>
      <td><%= objeto_valor(funcionario.carga_horaria) %></td>
      <% if current_usuario.local.escola%>
      <td><%= ambiente_alerta(funcionario) %></td>
      <% end %>
      <td><%= objeto_valor(funcionario.cargo) %></td>
      <td><%= objeto_valor(funcionario.quadro) %></td>
      <td><%= objeto_valor(funcionario.situacao) %></td>
      <td><%= objeto_valor(funcionario.disciplina_concurso) %></td>
      <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
        funcionario_path(funcionario), :class => 'btn btn-default btn-success btn-xs'%>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_funcionario_path(funcionario), :class => 'btn btn-default btn-xs' if aberto%>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        funcionario_path(funcionario),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' if aberto%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_funcionario_path,
:class => 'btn btn-success' if aberto%>

app/views/funcionarios/index_editor.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<% end %>
<%= form_for @q,:url=>administracao_listagem_funcionarios_path,:method=>:get do |f| %>

<%= f.label "Busca" %>
<%= f.text_field :nome_or_cpf_or_cadastro_cont %>
<%= f.select :quadro_cont,@quadros,include_blank: "Buscar por quadro",:selected=>:blank %>
<%= f.submit %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:cadastro) %></th>
      <th><%= model_class.human_attribute_name(:carga_horaria) %></th>
      <th><%= model_class.human_attribute_name(:ambiente) %></th>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:quadro) %></th>
      <th><%= model_class.human_attribute_name(:lotação) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_concurso_id) %></th>
      <% if !current_usuario.admin?%>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= link_to funcionario.nome,funcionario_path(funcionario) %></td>
        <td><%= objeto_valor(funcionario.cpf) %></td>
        <td><%= objeto_valor(funcionario.cadastro) %></td>
        <td><%= objeto_valor(funcionario.carga_horaria) %></td>
        <td><%= ambiente_alerta(funcionario) %></td>
        <td><%= objeto_valor(funcionario.cargo) %></td>
        <td><%= objeto_valor(funcionario.quadro) %></td>
        <td><%= objeto_valor(funcionario.local).upcase %></td>
        <td><%= objeto_valor(funcionario.disciplina_concurso) %></td>
         <% if !current_usuario.admin?%>
        <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
       funcionario_path(funcionario), :class => 'btn btn-default btn-xs' if current_usuario.admin?%>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_funcionario_path(funcionario), :class => 'btn btn-default btn-xs' if current_usuario.admin?%>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        funcionario_path(funcionario),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' if current_usuario.admin?%>
      </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @funcionarios, renderer: BootstrapPagination::Rails,:previous_label=>"<",:next_label=>">",:total_entries=>true%><br/>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_funcionario_path,
            :class => 'btn btn-success' %>

app/views/funcionarios/new.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
 <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>
<%= render :partial => 'form_escola' if current_usuario.local.escola?%>
<%= render :partial => 'form_secretaria' if !current_usuario.local.escola?%>